// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
<<<<<<< Updated upstream
    seed: "npx dotenv -e .env.local -- tsx prisma/seed.ts",
=======
    seed: "npx tsx prisma/seed.ts",
>>>>>>> Stashed changes
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
