-- ==========================================
-- 1. TABEL REFERENSI (MASTER DATA STATIC)
-- ==========================================
CREATE TABLE "ref_status_tugas" (
  "id" integer PRIMARY KEY,
  "nama" varchar
);

CREATE TABLE "ref_tipe_pekerjaan" (
  "id" integer PRIMARY KEY,
  "nama" varchar
);

CREATE TABLE "ref_status_ekuivalensi" (
  "id" integer PRIMARY KEY,
  "nama" varchar
);

CREATE TABLE "ref_status_import" (
  "id" integer PRIMARY KEY,
  "nama" varchar
);

-- ==========================================
-- 2. TABEL STRUKTUR KAMPUS
-- ==========================================
CREATE TABLE "semester" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama" varchar,
  "tahun" integer,
  "periode" varchar,
  "is_aktif" boolean DEFAULT false,
  "mulai" date,
  "selesai" date
);

CREATE TABLE "jurusan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_jurusan" varchar
);

CREATE TABLE "prodi" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jurusan_id" integer REFERENCES "jurusan"("id"),
  "nama_prodi" varchar
);

CREATE TABLE "kelas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prodi_id" integer REFERENCES "prodi"("id"),
  "nama_kelas" varchar
);

CREATE TABLE "gedung" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "jurusan_id" integer REFERENCES "jurusan"("id"),
  "nama_gedung" varchar
);

CREATE TABLE "ruangan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "gedung_id" integer REFERENCES "gedung"("id"),
  "nama_ruangan" varchar,
  "kode_ruangan" varchar
);

-- ==========================================
-- 3. TABEL USER & ROLE
-- ==========================================
CREATE TABLE "roles" (
  "id" integer PRIMARY KEY,
  "nama" varchar,
  "key_menu" jsonb,
  "key_condition" jsonb
);

CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "kata_sandi" varchar,
  "role_id" integer REFERENCES "roles"("id"),
  "created_at" timestamp DEFAULT (now())
);

-- ==========================================
-- 4. TABEL ENTITAS (MAHASISWA & STAF)
-- ==========================================
CREATE TABLE "mahasiswa" (
  "nim" varchar PRIMARY KEY,
  "user_id" integer UNIQUE REFERENCES "users"("user_id"),
  "nama" varchar
  -- Note: kelas_id dihapus dari sini (Pindah ke RegistrasiMahasiswa)
);

CREATE TABLE "staf" (
  "nip" varchar PRIMARY KEY,
  "user_id" integer UNIQUE REFERENCES "users"("user_id"),
  "nama" varchar,
  "jurusan_id" integer REFERENCES "jurusan"("id"),
  "tipe_staf" varchar
);

-- PERBAIKAN: TABEL REGISTRASI (SNAPSHOT PER SEMESTER)
CREATE TABLE "registrasi_mahasiswa" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nim" varchar REFERENCES "mahasiswa"("nim"),
  "semester_id" integer REFERENCES "semester"("id"),
  "kelas_id" integer REFERENCES "kelas"("id"),
  "status" varchar DEFAULT 'Aktif', -- Aktif, Cuti, Lulus
  UNIQUE ("nim", "semester_id")
);

-- ==========================================
-- 5. TABEL OPERASIONAL (KOMPEN & PEKERJAAN)
-- ==========================================
CREATE TABLE "import_log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staf_nip" varchar REFERENCES "staf"("nip"),
  "semester_id" integer REFERENCES "semester"("id"),
  "nama_file" varchar,
  "total_baris" integer,
  "sukses_baris" integer,
  "error_details" jsonb,
  "status_import_id" integer REFERENCES "ref_status_import"("id"),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "kompen_awal" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nim" varchar REFERENCES "mahasiswa"("nim"),
  "semester_id" integer REFERENCES "semester"("id"),
  "import_id" integer REFERENCES "import_log"("id"),
  "total_jam_wajib" float,
  "created_at" timestamp DEFAULT (now()),
  UNIQUE ("nim", "semester_id")
);

CREATE TABLE "daftar_pekerjaan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staf_nip" varchar REFERENCES "staf"("nip"),
  "semester_id" integer REFERENCES "semester"("id"),
  "judul" varchar,
  "deskripsi" text,
  "tipe_pekerjaan_id" integer REFERENCES "ref_tipe_pekerjaan"("id"),
  "poin_jam" float,
  "kuota" integer,
  "ruangan_id" integer REFERENCES "ruangan"("id"),
  "is_aktif" boolean DEFAULT true,
  "tanggal_mulai" date,
  "tanggal_selesai" date,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "penugasan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pekerjaan_id" integer REFERENCES "daftar_pekerjaan"("id"),
  "nim" varchar REFERENCES "mahasiswa"("nim"),
  "status_tugas_id" integer REFERENCES "ref_status_tugas"("id"),
  "detail_pengerjaan" jsonb,
  "catatan_verifikasi" text,
  "diverifikasi_oleh_nip" varchar REFERENCES "staf"("nip"),
  "waktu_verifikasi" timestamp,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "ekuivalensi_kelas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "kelas_id" integer REFERENCES "kelas"("id"),
  "semester_id" integer REFERENCES "semester"("id"),
  "penanggung_jawab_nim" varchar REFERENCES "mahasiswa"("nim"),
  "nota_url" text,
  "nominal_total" decimal,
  "jam_diakui" float,
  "status_ekuivalensi_id" integer REFERENCES "ref_status_ekuivalensi"("id"),
  "verified_by_nip" varchar REFERENCES "staf"("nip"),
  "catatan" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "log_potong_jam" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nim" varchar REFERENCES "mahasiswa"("nim"),
  "semester_id" integer REFERENCES "semester"("id"),
  "penugasan_id" integer REFERENCES "penugasan"("id"),
  "ekuivalensi_id" integer REFERENCES "ekuivalensi_kelas"("id"),
  "jam_dikurangi" float,
  "keterangan" text,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "pengaturan_sistem" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "grup" varchar,
  "key" varchar UNIQUE,
  "value" varchar,
  "tipe_data" varchar,
  "keterangan" text
);

-- 1. VIEW PROFIL LENGKAP MAHASISWA (BERDASARKAN SEMESTER AKTIF)
-- Digunakan untuk Navbar dan Dashboard agar langsung muncul Nama, Kelas, dan Prodi
CREATE OR REPLACE VIEW public.v_mahasiswa_aktif AS
 SELECT 
    m.nim,
    m.nama,
    u.email,
    r.semester_id,
    r.status as status_registrasi,
    k.nama_kelas,
    p.nama_prodi,
    j.nama_jurusan,
    s.is_aktif as is_semester_aktif
   FROM public.mahasiswa m
     JOIN public.users u ON u.user_id = m.user_id
     JOIN public.registrasi_mahasiswa r ON r.nim = m.nim
     JOIN public.semester s ON s.id = r.semester_id
     JOIN public.kelas k ON k.id = r.kelas_id
     JOIN public.prodi p ON p.id = k.prodi_id
     JOIN public.jurusan j ON j.id = p.jurusan_id;

-- 2. VIEW SISA JAM KOMPEN (LOGIKA UTAMA SISTEM)
-- Menghitung total utang jam dikurangi jam yang sudah diselesaikan (log_potong_jam)
CREATE OR REPLACE VIEW public.v_sisa_kompen AS
 SELECT 
    ka.nim,
    ka.semester_id,
    ka.total_jam_wajib,
    COALESCE(sum(lpj.jam_dikurangi), 0) AS jam_selesai,
    (ka.total_jam_wajib - COALESCE(sum(lpj.jam_dikurangi), 0)) AS sisa_jam
   FROM public.kompen_awal ka
     LEFT JOIN public.log_potong_jam lpj ON lpj.nim = ka.nim AND lpj.semester_id = ka.semester_id
  GROUP BY ka.nim, ka.semester_id, ka.total_jam_wajib;

-- 3. VIEW MONITORING PEKERJAAN (UNTUK STAF)
-- Melihat sisa kuota tiap lowongan pekerjaan secara real-time
CREATE OR REPLACE VIEW public.v_status_pekerjaan AS
 SELECT 
    dp.id as pekerjaan_id,
    dp.judul,
    dp.kuota,
    dp.poin_jam,
    dp.is_aktif,
    count(p.id) FILTER (WHERE p.status_tugas_id != 5) AS kuota_terisi, -- Kecuali yang ditolak
    (dp.kuota - count(p.id) FILTER (WHERE p.status_tugas_id != 5)) AS sisa_slot
   FROM public.daftar_pekerjaan dp
     LEFT JOIN public.penugasan p ON p.pekerjaan_id = dp.id
  GROUP BY dp.id;

  -- 1. INSERT DATA JURUSAN & KELAS (DUMMY)
INSERT INTO public.jurusan (nama_jurusan) VALUES ('Teknik Elektro');
INSERT INTO public.prodi (jurusan_id, nama_prodi) VALUES (1, 'D3 Teknik Informatika');
INSERT INTO public.kelas (prodi_id, nama_kelas) VALUES (1, 'IK-2C');

-- 2. INSERT SEMESTER AKTIF
INSERT INTO public.semester (nama, tahun, periode, is_aktif, mulai, selesai) 
VALUES ('Ganjil 2025/2026', 2026, 'Ganjil', true, '2026-09-01', '2027-01-30');

-- 3. INSERT USER (Password: Polines123!)
INSERT INTO public.users (user_id, email, kata_sandi, role_id) VALUES
(101, 'admin@polines.ac.id', '$2b$10$EPZ9S63mS9.vH6A.9m99u.7N.xXfH2/6P6X9.9m99u.7N.xXfH2/', 1), -- Admin
(102, 'dosen@polines.ac.id', '$2b$10$EPZ9S63mS9.vH6A.9m99u.7N.xXfH2/6P6X9.9m99u.7N.xXfH2/', 4), -- Dosen
(103, 'akbar@mhs.polines.ac.id', '$2b$10$EPZ9S63mS9.vH6A.9m99u.7N.xXfH2/6P6X9.9m99u.7N.xXfH2/', 3); -- Mahasiswa

-- 4. INSERT PROFIL ENTITAS
INSERT INTO public.staf (nip, user_id, nama, jurusan_id, tipe_staf) VALUES
('198001012024011001', 101, 'Super Admin Kompen', 1, 'admin'),
('197505052005011002', 102, 'Sir Danu Prakoso', 1, 'dosen');

INSERT INTO public.mahasiswa (nim, user_id, nama) VALUES
('33424202', 103, 'Akbar Rama');

-- 5. REGISTRASI SEMESTER (Kunci agar Mahasiswa Aktif muncul di Dashboard)
INSERT INTO public.registrasi_mahasiswa (nim, semester_id, kelas_id, status) VALUES
('33424202', 1, 1, 'Aktif');
